### ISSUE TITLE
After import web3 get from Crypto.Protocol.KDF import scrypt  ImportError: cannot import name 'scrypt'

### ISSUE THREAD

**Issue by 4c656554** [ethereum/eth-keyfile#11]
* Version: 4.0.0b11
* Python: 3.6.4
* OS: win7

### What was wrong?

After `import web3`

I was getting an error trace ending in:
```
    from Crypto.Protocol.KDF import scrypt

ImportError: cannot import name 'scrypt'
```

(N.b. I'm not sure if this is an error due to some possible installation error I made)

Please include any of the following that are applicable:

* The code which produced the error:
 
https://github.com/ethereum/eth-keyfile/blob/master/eth_keyfile/keyfile.py#L7

* The full output of the error
Traceback (most recent call last):

```
  File "<ipython-input-4-818c60069f6c>", line 1, in <module>
    import web3

  File "Z:\MyDirs\lib\site-packages\web3\__init__.py", line 7, in <module>
    from eth_account import Account  # noqa: E402

  File "Z:\MyDirs\lib\site-packages\eth_account-0.1.0a2-py3.6.egg\eth_account\__init__.py", line 1, in <module>
    from eth_account.account import Account  # noqa: F401

  File "Z:\MyDirs\lib\site-packages\eth_account-0.1.0a2-py3.6.egg\eth_account\account.py", line 10, in <module>
    from eth_keyfile import (

  File "Z:\MyDirs\lib\site-packages\eth_keyfile-0.5.1-py3.6.egg\eth_keyfile\__init__.py", line 7, in <module>
    from eth_keyfile.keyfile import (  # noqa: F401

  File "Z:\MyDirs\lib\site-packages\eth_keyfile-0.5.1-py3.6.egg\eth_keyfile\keyfile.py", line 7, in <module>
    from Crypto.Protocol.KDF import scrypt

ImportError: cannot import name 'scrypt'
```

### How can it be fixed?

I fixed this by installing scrypt:

`pip install scrypt`

an then replacing:

`from Crypto.Protocol.KDF import scrypt`

with:

`import scrypt`

However, I don't know if the libraries are equivalent...

Fill this section in if you know how this could or should be fixed.

**Comment by pipermerriam** [comment]
Can you provide the full output from `pip freeze`.  It looks like pycryptodome may have failed to install?  Can you see if you are able to `import Crypto`?

**Comment by 4c656554** [comment]
Sure thing:

```
pip freeze
alabaster==0.7.10
anaconda-client==1.6.9
anaconda-navigator==1.7.0
anaconda-project==0.8.2
asn1crypto==0.24.0
astroid==1.6.1
astropy==2.0.3
attrdict==2.0.0
attrs==17.4.0
Babel==2.5.3
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.6.0
bitarray==0.8.1
bkcharts==0.2
blaze==0.11.3
bleach==2.1.2
bokeh==0.12.13
boto==2.48.0
Bottleneck==1.2.1
certifi==2018.1.18
cffi==1.11.4
chardet==3.0.4
click==6.7
cloudpickle==0.5.2
clyent==1.2.2
colorama==0.3.9
comtypes==1.1.4
conda==4.4.10
conda-build==3.4.1
conda-verify==2.0.0
contextlib2==0.5.5
crypto==1.4.1
cryptography==2.1.4
cycler==0.10.0
Cython==0.27.3
cytoolz==0.9.0.1
dask==0.16.1
datashape==0.5.4
decorator==4.2.1
distributed==1.20.2
docutils==0.14
entrypoints==0.2.3
et-xmlfile==1.0.1
eth-abi==1.0.0
eth-account==0.1.0a2
eth-hash==0.1.0
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.0
eth-utils==1.0.1
fastcache==1.0.2
filelock==2.0.13
Flask==0.12.2
Flask-Cors==3.0.3
gevent==1.2.2
glob2==0.6
greenlet==0.4.12
h5py==2.7.1
heapdict==1.0.0
hexbytes==0.1.0
html5lib==1.0.1
idna==2.6
imageio==2.2.0
imagesize==0.7.1
ipython==6.2.1
ipython-genutils==0.2.0
ipywidgets==7.1.1
isort==4.2.15
itsdangerous==0.24
jdcal==1.3
jedi==0.11.1
Jinja2==2.10
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.2
jupyter-console==5.2.0
jupyter-core==4.4.0
jupyterlab==0.31.4
jupyterlab-launcher==0.10.2
lazy-object-proxy==1.3.1
llvmlite==0.21.0
locket==0.2.0
lru-dict==1.1.6
lxml==4.1.1
MarkupSafe==1.0
matplotlib==2.1.2
mccabe==0.6.1
menuinst==1.4.11
mistune==0.8.3
mpmath==1.0.0
msgpack-python==0.5.1
multipledispatch==0.4.9
Naked==0.1.31
navigator-updater==0.1.0
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.1
nltk==3.2.5
nose==1.3.7
notebook==5.4.0
numba==0.36.2
numexpr==2.6.4
numpy==1.14.0
numpydoc==0.7.0
odo==0.5.1
olefile==0.45.1
openpyxl==2.4.10
packaging==16.8
pandas==0.22.0
pandocfilters==1.4.2
parso==0.1.1
partd==0.3.8
path.py==10.5
pathlib2==2.3.0
patsy==0.5.0
pep8==1.7.1
pickleshare==0.7.4
Pillow==5.0.0
pkginfo==1.4.1
pluggy==0.6.0
ply==3.10
prompt-toolkit==1.0.15
psutil==5.4.3
py==1.5.2
pycodestyle==2.3.1
pycosat==0.6.3
pycparser==2.18
pycrypto==2.6.1
pycryptodome==3.5.1
pycurl==7.43.0.1
pyflakes==1.6.0
Pygments==2.2.0
pylint==1.8.2
pyodbc==4.0.22
pyOpenSSL==17.5.0
pyparsing==2.2.0
pysha3==1.0.2
PySocks==1.6.7
pytest==3.3.2
python-dateutil==2.6.1
pytz==2017.3
PyWavelets==0.5.2
pywin32==222
pywinpty==0.5
PyYAML==3.12
pyzmq==16.0.3
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.3.1
requests==2.18.4
rlp==0.6.0
rope==0.10.7
ruamel-yaml==0.15.35
scikit-image==0.13.1
scikit-learn==0.19.1
scipy==1.0.0
scrypt==0.8.6
seaborn==0.8.1
Send2Trash==1.4.2
shellescape==3.4.1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
snowballstemmer==1.2.1
sortedcollections==0.5.3
sortedcontainers==1.5.9
Sphinx==1.6.6
sphinxcontrib-websupport==1.0.1
spyder==3.2.6
SQLAlchemy==1.2.1
statsmodels==0.8.0
sympy==1.1.1
tables==3.4.2
tblib==1.3.2
terminado==0.8.1
testpath==0.3.1
toolz==0.9.0
tornado==4.5.3
traitlets==4.3.2
typing==3.6.2
unicodecsv==0.14.1
urllib3==1.22
wcwidth==0.1.7
web3==4.0.0b11
webencodings==0.5.1
Werkzeug==0.14.1
widgetsnbextension==3.1.0
win-inet-pton==1.0.1
win-unicode-console==0.5
wincertstore==0.2
wrapt==1.10.11
xlrd==1.1.0
XlsxWriter==1.0.2
xlwings==0.11.5
xlwt==1.3.0
zict==0.1.3
```

**Comment by 4c656554** [comment]
More info... Note the install didn't go smoothly. On the first attempt nothing web3 related was found in modules.keys:

```
import sys
sys.module.keys()
```

Seemed to work on second attempt (my python env variables weren't correct on first go).


Thank you for putting this module together btw!

**Comment by pipermerriam** [comment]
np, I'm interpreting this to indicate that this issue is resolved?  If not, let me know.

**Comment by 4c656554** [comment]
Yes thanks,

and yes I was able to install Crypto... (in answer to above)

Though it (web3.py) only worked for me after making above change (separate import scrypt)

Looking at the code, KDF.py in Crypto library, it doesn't seem to have scrypt as a component?

Perhaps scrypt could be added as separate dependency...

**Comment by pipermerriam** [comment]
I just tested on a fresh python environment with `pycryptodome==3.5.1` installed and I was able to perform the import (albeit on an osx box) but that shouldn't matter.  Are you able to make other imports from the `Crypto` namespace?  `from Crypto.Protocol import KDF`?

**Comment by pipermerriam** [comment]
> Perhaps scrypt could be added as separate dependency...

We use the scrypt implementation from `pycryptodome` so you should not need the scrypt library itself.

**Comment by 4c656554** [comment]
..... actually it does!  must've made a type on first attempt

**Comment by parin13** [comment]
solved it by updating web3:

> sudp pip3 install --upgrade web3
