### ISSUE TITLE
ImportError: cannot import name 'scrypt'

### ISSUE THREAD

**Issue by shawnpringle** [ethereum/eth-keyfile#16]
* Version: 0.5.1
* Python: 3.6
* OS: linux

### What was wrong?

Attempting to import eth-keyfile results in the following exception and traceback:

```python
>>> import eth_keyfile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/eth_keyfile-0.5.1-py3.6.egg/eth_keyfile/__init__.py", line 7, in <module>
    from eth_keyfile.keyfile import (  # noqa: F401
  File "/usr/local/lib/python3.6/site-packages/eth_keyfile-0.5.1-py3.6.egg/eth_keyfile/keyfile.py", line 7, in <module>
    from Crypto.Protocol.KDF import scrypt
ImportError: cannot import name 'scrypt'

```

### How can it be fixed?

Perhaps I am missing a dependency?

**Comment by pipermerriam** [comment]
Two requests:

- Can you provide the output from `pip freeze`?
- Can you check whether you can perform that import directly in a python REPL?

**Comment by shawnpringle** [comment]
```
pip freeze
alabaster==0.7.10
altgraph==0.14
appdirs==1.4.3
asn1crypto==0.24.0
asyncio==3.4.3
attrdict==2.0.0
Babel==2.5.3
beem==0.19.50
bitshares==0.1.22
certifi==2018.1.18
cffi==1.11.5
chardet==3.0.4
click==6.7
colorama==0.3.6
configparser==3.5.0
crypto==1.4.1
cryptography==2.1.4
cytoolz==0.9.0.1
dateparser==0.6.0
dateutils==0.6.6
diff-match-patch==20121119
docutils==0.14
ecdsa==0.13
eth-abi==1.2.0
eth-account==0.3.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-typing==1.3.0
eth-utils==1.2.2
Events==0.3
funcy==1.10.1
future==0.16.0
graphenelib==0.6.6
hexbytes==0.1.0
humanize==0.5.1
idna==2.6
imagesize==1.0.0
jeepney==0.3.1
Jinja2==2.10
keyring==11.0.0
keyring-jeepney==0.2
langdetect==1.0.7
legacy==0.1.6
lru-dict==1.1.6
macholib==1.8
MarkupSafe==1.0
maya==0.3.2
mysql-connector==2.1.4
Naked==0.1.31
olefile==0.44
onetimepass==1.0.1
packaging==17.1
parsimonious==0.8.0
pathlib==1.0.1
pbr==4.0.4
pdfrw==0.4
pefile==2017.9.3
pendulum==1.2.5
pew==1.1.2
Pillow==4.0.0
pipenv==11.1.4
piston-lib==0.5.4
prettytable==0.7.2
pycparser==2.18
pycrypto==2.6.1
pycryptodome==3.6.6
pycryptodomex==3.5.1
Pygments==2.2.0
PyInstaller==3.3
pylibscrypt==1.6.1
pyparsing==2.2.0
python-bittrex==0.2.1
python-dateutil==2.6.1
python-frontmatter==0.2.1
pytz==2018.3
pytzdata==2017.2.2
PyYAML==3.12
regex==2017.7.28
requests==2.18.4
rlp==1.0.2
ruamel.yaml==0.15.34
scrypt==0.8.6
SecretStorage==2.3.1
shellescape==3.4.1
six==1.11.0
snowballstemmer==1.2.1
Sphinx==1.7.1
sphinx-click==1.2.0
sphinx-rtd-theme==0.4.0
sphinxcontrib-websupport==1.0.1
steem==0.18.103
steem-piston==0.4.1
toolz==0.9.0
tzlocal==1.4
ujson==1.35
urllib3==1.22
virtualenv==15.1.0
virtualenv-clone==0.3.0
voluptuous==0.11.1
w3lib==1.19.0
web3==4.7.1
websocket-client==0.47.0
websockets==2.0
```

I don't understand the second part of the question.  Maybe you are asking whether I install via pip?
```shell
pip install eth-keyfile
```

```
Requirement already satisfied: eth-keyfile in /usr/local/lib/python3.6/site-packages/eth_keyfile-0.5.1-py3.6.egg (0.5.1)
Requirement already satisfied: cytoolz<1.0.0,>=0.9.0 in /usr/local/lib/python3.6/site-packages/cytoolz-0.9.0.1-py3.6-linux-i686.egg (from eth-keyfile) (0.9.0.1)
Requirement already satisfied: eth-keys<1.0.0,>=0.1.0-beta.4 in /usr/local/lib/python3.6/site-packages/eth_keys-0.2.0b3-py3.6.egg (from eth-keyfile) (0.2.0b3)
Requirement already satisfied: eth-utils<2.0.0,>=1.0.0-beta.1 in /usr/local/lib/python3.6/site-packages/eth_utils-1.2.2-py3.6.egg (from eth-keyfile) (1.2.2)
Requirement already satisfied: pycryptodome<4.0.0,>=3.4.7 in /usr/local/lib/python3.6/site-packages/pycryptodome-3.6.6-py3.6-linux-i686.egg (from eth-keyfile) (3.6.6)
Requirement already satisfied: toolz>=0.8.0 in /home/alumno/.local/lib/python3.6/site-packages (from cytoolz<1.0.0,>=0.9.0->eth-keyfile) (0.9.0)
Requirement already satisfied: eth-hash<1.0.0,>=0.1.0 in /usr/local/lib/python3.6/site-packages/eth_hash-0.2.0-py3.6.egg (from eth-utils<2.0.0,>=1.0.0-beta.1->eth-keyfile) (0.2.0)
Requirement already satisfied: eth-typing<2.0.0,>=1.3.0 in /usr/local/lib/python3.6/site-packages/eth_typing-1.3.0-py3.6.egg (from eth-utils<2.0.0,>=1.0.0-beta.1->eth-keyfile) (1.3.0)
```

**Comment by pipermerriam** [comment]
REPL question was whether the following works:

```python
>>> from Crypto.Protocol.KDF import scrypt
# ? does it work or does it throw an error ?
```

**Comment by shawnpringle** [comment]
Yes, it throws the same error.

**Comment by pipermerriam** [comment]
It looks like the error may be to do with having both `pycrypto` and `pycryptodome` installed.  Try uninstalling `pycrypto` (and maybe re-installing `pycryptodome`)

**Comment by fselmo** [comment]
stale / resolved?
