### ISSUE TITLE
extract_key_from_keyfile can't load file from myetherwallet.com wallet json file

### ISSUE THREAD

**Issue by aaron315** [ethereum/eth-keyfile#8]
* Version: x.x.x
* Python: 2.7/3.4/3.5
* OS: osx/linux/win

### What was wrong?

Please include any of the following that are applicable:

>>> extract_key_from_keyfile('/Users/aaronluo/Downloads/UTC--2018-02-06T10-13-26.198Z--044a4f5cc94803abc7455e02024e0636c0e10c4d','password'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronluo/work/ve/ico-backend/lib/python3.6/site-packages/eth_keyfile/keyfile.py", line 54, in extract_key_from_keyfile
    private_key = decode_keyfile_json(keyfile_json, password)
  File "/Users/aaronluo/work/ve/ico-backend/lib/python3.6/site-packages/eth_keyfile/keyfile.py", line 47, in decode_keyfile_json
    return _decode_keyfile_json_v3(keyfile_json, password)
  File "/Users/aaronluo/work/ve/ico-backend/lib/python3.6/site-packages/eth_keyfile/keyfile.py", line 133, in _decode_keyfile_json_v3
    crypto = keyfile_json['crypto']
KeyError: 'crypto'

### How can it be fixed?

because in myetherwallet.com wallet json file is "Crypto" not "crypto"

**Comment by pipermerriam** [comment]
I'm good adding support for this.  Probably through a step which *normalizes* all of the keys to their lowercase versions (and some validation to be sure we aren't overriding any keys in the case that somehow both the uppercase and lowercase versions are present.

**Comment by pipermerriam** [comment]
If you'd like to submit a patch for this I'd be happy to review and get it merged and released for you.

**Comment by Bhargavasomu** [comment]
@pipermerriam I was going through this and came to know that https://github.com/ethereum/eth-keyfile/pull/10 fixes it. So I guess this issue could be closed.
